### ISSUE TITLE
Why do you save all the data to a database?

### ISSUE THREAD

**Issue by decrek** [gijslaarman/progressive-web-apps-1920#6]
It seems you are saving the data to a database, both images as the actual team data. What is the idea behind this? What would be the benefit of this over directly calling the API when a user request a certain url?

**Comment by decrek** [comment]
You could move `/utils/init.js` to the build and you are a few steps away from a static website. Your data could be static json files.

**Comment by gijslaarman** [comment]
Great suggestion! I scrapped the database, now on build the server generates a JSON in utils & saves all team crests/images inside the public/img folder.
